STREAK_BONUS_3      = 2
STREAK_BONUS_5      = 3
BASE_POINTS         = 1
ACE_MULTIPLIER      = 2
RISK_MULTIPLIER     = 2
RISK_LIFE_PENALTY   = 2
NORMAL_LIFE_PENALTY = 1


CARDHUNT_DEFAULT_GRID_SIZE = 3
CARDHUNT_STARTING_LIVES = 4
CARDHUNT_POINTS_PER = 1